// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.27.3
// source: convert.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordToPdfReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docu *DocuChunk `protobuf:"bytes,1,opt,name=docu,proto3" json:"docu,omitempty"`
}

func (x *WordToPdfReq) Reset() {
	*x = WordToPdfReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordToPdfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordToPdfReq) ProtoMessage() {}

func (x *WordToPdfReq) ProtoReflect() protoreflect.Message {
	mi := &file_convert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordToPdfReq.ProtoReflect.Descriptor instead.
func (*WordToPdfReq) Descriptor() ([]byte, []int) {
	return file_convert_proto_rawDescGZIP(), []int{0}
}

func (x *WordToPdfReq) GetDocu() *DocuChunk {
	if x != nil {
		return x.Docu
	}
	return nil
}

type WordToPdfRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docu *DocuChunk `protobuf:"bytes,1,opt,name=docu,proto3" json:"docu,omitempty"`
}

func (x *WordToPdfRes) Reset() {
	*x = WordToPdfRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordToPdfRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordToPdfRes) ProtoMessage() {}

func (x *WordToPdfRes) ProtoReflect() protoreflect.Message {
	mi := &file_convert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordToPdfRes.ProtoReflect.Descriptor instead.
func (*WordToPdfRes) Descriptor() ([]byte, []int) {
	return file_convert_proto_rawDescGZIP(), []int{1}
}

func (x *WordToPdfRes) GetDocu() *DocuChunk {
	if x != nil {
		return x.Docu
	}
	return nil
}

var File_convert_proto protoreflect.FileDescriptor

var file_convert_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x1a, 0x0a, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x64, 0x54, 0x6f, 0x50, 0x64,
	0x66, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x75, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x75, 0x22, 0x33, 0x0a, 0x0c, 0x57, 0x6f, 0x72,
	0x64, 0x54, 0x6f, 0x50, 0x64, 0x66, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x6f, 0x63,
	0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x44,
	0x6f, 0x63, 0x75, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x04, 0x64, 0x6f, 0x63, 0x75, 0x32, 0x48,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x12, 0x3d, 0x0a, 0x09, 0x57, 0x6f, 0x72,
	0x64, 0x54, 0x6f, 0x50, 0x64, 0x66, 0x12, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x2e, 0x57, 0x6f, 0x72, 0x64, 0x54, 0x6f, 0x50, 0x64, 0x66, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x54, 0x6f, 0x50, 0x64,
	0x66, 0x52, 0x65, 0x73, 0x28, 0x01, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_convert_proto_rawDescOnce sync.Once
	file_convert_proto_rawDescData = file_convert_proto_rawDesc
)

func file_convert_proto_rawDescGZIP() []byte {
	file_convert_proto_rawDescOnce.Do(func() {
		file_convert_proto_rawDescData = protoimpl.X.CompressGZIP(file_convert_proto_rawDescData)
	})
	return file_convert_proto_rawDescData
}

var file_convert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_convert_proto_goTypes = []interface{}{
	(*WordToPdfReq)(nil), // 0: convert.WordToPdfReq
	(*WordToPdfRes)(nil), // 1: convert.WordToPdfRes
	(*DocuChunk)(nil),    // 2: word.DocuChunk
}
var file_convert_proto_depIdxs = []int32{
	2, // 0: convert.WordToPdfReq.docu:type_name -> word.DocuChunk
	2, // 1: convert.WordToPdfRes.docu:type_name -> word.DocuChunk
	0, // 2: convert.Convert.WordToPdf:input_type -> convert.WordToPdfReq
	1, // 3: convert.Convert.WordToPdf:output_type -> convert.WordToPdfRes
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_convert_proto_init() }
func file_convert_proto_init() {
	if File_convert_proto != nil {
		return
	}
	file_word_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_convert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordToPdfReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_convert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordToPdfRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_convert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_convert_proto_goTypes,
		DependencyIndexes: file_convert_proto_depIdxs,
		MessageInfos:      file_convert_proto_msgTypes,
	}.Build()
	File_convert_proto = out.File
	file_convert_proto_rawDesc = nil
	file_convert_proto_goTypes = nil
	file_convert_proto_depIdxs = nil
}
