// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v5.27.3
// source: word.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocuValueType int32

const (
	DocuValueType_TEXT  DocuValueType = 0
	DocuValueType_IMAGE DocuValueType = 1
)

// Enum value maps for DocuValueType.
var (
	DocuValueType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
	}
	DocuValueType_value = map[string]int32{
		"TEXT":  0,
		"IMAGE": 1,
	}
)

func (x DocuValueType) Enum() *DocuValueType {
	p := new(DocuValueType)
	*p = x
	return p
}

func (x DocuValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocuValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_word_proto_enumTypes[0].Descriptor()
}

func (DocuValueType) Type() protoreflect.EnumType {
	return &file_word_proto_enumTypes[0]
}

func (x DocuValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocuValueType.Descriptor instead.
func (DocuValueType) EnumDescriptor() ([]byte, []int) {
	return file_word_proto_rawDescGZIP(), []int{0}
}

type DocuChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunks [][]byte `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
}

func (x *DocuChunk) Reset() {
	*x = DocuChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_word_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocuChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocuChunk) ProtoMessage() {}

func (x *DocuChunk) ProtoReflect() protoreflect.Message {
	mi := &file_word_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocuChunk.ProtoReflect.Descriptor instead.
func (*DocuChunk) Descriptor() ([]byte, []int) {
	return file_word_proto_rawDescGZIP(), []int{0}
}

func (x *DocuChunk) GetChunks() [][]byte {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type DocuValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  DocuValueType `protobuf:"varint,1,opt,name=type,proto3,enum=word.DocuValueType" json:"type,omitempty"`
	Key   string        `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value string        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DocuValue) Reset() {
	*x = DocuValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_word_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocuValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocuValue) ProtoMessage() {}

func (x *DocuValue) ProtoReflect() protoreflect.Message {
	mi := &file_word_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocuValue.ProtoReflect.Descriptor instead.
func (*DocuValue) Descriptor() ([]byte, []int) {
	return file_word_proto_rawDescGZIP(), []int{1}
}

func (x *DocuValue) GetType() DocuValueType {
	if x != nil {
		return x.Type
	}
	return DocuValueType_TEXT
}

func (x *DocuValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DocuValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DocuWord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body   []*DocuValue `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
	Header []*DocuValue `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty"`
	Footer []*DocuValue `protobuf:"bytes,3,rep,name=footer,proto3" json:"footer,omitempty"`
}

func (x *DocuWord) Reset() {
	*x = DocuWord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_word_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocuWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocuWord) ProtoMessage() {}

func (x *DocuWord) ProtoReflect() protoreflect.Message {
	mi := &file_word_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocuWord.ProtoReflect.Descriptor instead.
func (*DocuWord) Descriptor() ([]byte, []int) {
	return file_word_proto_rawDescGZIP(), []int{2}
}

func (x *DocuWord) GetBody() []*DocuValue {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DocuWord) GetHeader() []*DocuValue {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DocuWord) GetFooter() []*DocuValue {
	if x != nil {
		return x.Footer
	}
	return nil
}

type WordApplyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*WordApplyReq_Word
	//	*WordApplyReq_Docu
	Request isWordApplyReq_Request `protobuf_oneof:"request"`
}

func (x *WordApplyReq) Reset() {
	*x = WordApplyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_word_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordApplyReq) ProtoMessage() {}

func (x *WordApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_word_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordApplyReq.ProtoReflect.Descriptor instead.
func (*WordApplyReq) Descriptor() ([]byte, []int) {
	return file_word_proto_rawDescGZIP(), []int{3}
}

func (m *WordApplyReq) GetRequest() isWordApplyReq_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *WordApplyReq) GetWord() *DocuWord {
	if x, ok := x.GetRequest().(*WordApplyReq_Word); ok {
		return x.Word
	}
	return nil
}

func (x *WordApplyReq) GetDocu() *DocuChunk {
	if x, ok := x.GetRequest().(*WordApplyReq_Docu); ok {
		return x.Docu
	}
	return nil
}

type isWordApplyReq_Request interface {
	isWordApplyReq_Request()
}

type WordApplyReq_Word struct {
	Word *DocuWord `protobuf:"bytes,1,opt,name=word,proto3,oneof"`
}

type WordApplyReq_Docu struct {
	Docu *DocuChunk `protobuf:"bytes,2,opt,name=docu,proto3,oneof"`
}

func (*WordApplyReq_Word) isWordApplyReq_Request() {}

func (*WordApplyReq_Docu) isWordApplyReq_Request() {}

type WordApplyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docu *DocuChunk `protobuf:"bytes,1,opt,name=docu,proto3" json:"docu,omitempty"`
}

func (x *WordApplyRes) Reset() {
	*x = WordApplyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_word_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordApplyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordApplyRes) ProtoMessage() {}

func (x *WordApplyRes) ProtoReflect() protoreflect.Message {
	mi := &file_word_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordApplyRes.ProtoReflect.Descriptor instead.
func (*WordApplyRes) Descriptor() ([]byte, []int) {
	return file_word_proto_rawDescGZIP(), []int{4}
}

func (x *WordApplyRes) GetDocu() *DocuChunk {
	if x != nil {
		return x.Docu
	}
	return nil
}

var File_word_proto protoreflect.FileDescriptor

var file_word_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x23, 0x0a, 0x09, 0x44, 0x6f, 0x63, 0x75, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x22, 0x5c, 0x0a, 0x09, 0x44, 0x6f, 0x63, 0x75, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75, 0x57, 0x6f,
	0x72, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x44,
	0x6f, 0x63, 0x75, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x27, 0x0a, 0x06, 0x66, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x06, 0x66, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x22, 0x66, 0x0a, 0x0c, 0x57, 0x6f, 0x72,
	0x64, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x04, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x44,
	0x6f, 0x63, 0x75, 0x57, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x25, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x77, 0x6f, 0x72, 0x64, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x6f, 0x63, 0x75, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x33, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65,
	0x73, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x52, 0x04, 0x64, 0x6f, 0x63, 0x75, 0x2a, 0x24, 0x0a, 0x0d, 0x44, 0x6f, 0x63, 0x75, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x01, 0x32, 0x3b, 0x0a, 0x04,
	0x57, 0x6f, 0x72, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x2e,
	0x77, 0x6f, 0x72, 0x64, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x12, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x41, 0x70, 0x70,
	0x6c, 0x79, 0x52, 0x65, 0x73, 0x28, 0x01, 0x30, 0x01, 0x42, 0x11, 0x5a, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0xaa, 0x02, 0x06, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_word_proto_rawDescOnce sync.Once
	file_word_proto_rawDescData = file_word_proto_rawDesc
)

func file_word_proto_rawDescGZIP() []byte {
	file_word_proto_rawDescOnce.Do(func() {
		file_word_proto_rawDescData = protoimpl.X.CompressGZIP(file_word_proto_rawDescData)
	})
	return file_word_proto_rawDescData
}

var file_word_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_word_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_word_proto_goTypes = []interface{}{
	(DocuValueType)(0),   // 0: word.DocuValueType
	(*DocuChunk)(nil),    // 1: word.DocuChunk
	(*DocuValue)(nil),    // 2: word.DocuValue
	(*DocuWord)(nil),     // 3: word.DocuWord
	(*WordApplyReq)(nil), // 4: word.WordApplyReq
	(*WordApplyRes)(nil), // 5: word.WordApplyRes
}
var file_word_proto_depIdxs = []int32{
	0, // 0: word.DocuValue.type:type_name -> word.DocuValueType
	2, // 1: word.DocuWord.body:type_name -> word.DocuValue
	2, // 2: word.DocuWord.header:type_name -> word.DocuValue
	2, // 3: word.DocuWord.footer:type_name -> word.DocuValue
	3, // 4: word.WordApplyReq.word:type_name -> word.DocuWord
	1, // 5: word.WordApplyReq.docu:type_name -> word.DocuChunk
	1, // 6: word.WordApplyRes.docu:type_name -> word.DocuChunk
	4, // 7: word.Word.Apply:input_type -> word.WordApplyReq
	5, // 8: word.Word.Apply:output_type -> word.WordApplyRes
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_word_proto_init() }
func file_word_proto_init() {
	if File_word_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_word_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocuChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_word_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocuValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_word_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocuWord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_word_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordApplyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_word_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordApplyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_word_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*WordApplyReq_Word)(nil),
		(*WordApplyReq_Docu)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_word_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_word_proto_goTypes,
		DependencyIndexes: file_word_proto_depIdxs,
		EnumInfos:         file_word_proto_enumTypes,
		MessageInfos:      file_word_proto_msgTypes,
	}.Build()
	File_word_proto = out.File
	file_word_proto_rawDesc = nil
	file_word_proto_goTypes = nil
	file_word_proto_depIdxs = nil
}
